### ISSUE TITLE
[AvdanOS] - BURG as an option for AvdanOS

### ISSUE THREAD

**Issue by akane6704** [Avdan-OS/suggestions#2]
Many distros don't integrate BURG by default, also it looks very clean, so i thought it would be a great idea, to make it an option in the installer

The installer will tell to the user, if install a bootloader, such as GRUB or BURG, or not install a bootloader

**Comment by Trynera** [comment]
I disagree as it doesn't over much more but takes up more space. also valnurabilitys that are on grub will be fixed earlier than on burg

**Comment by dorakuflu** [comment]
I don't think that on an OS like AvdanOS, many users will want to customize Grub. We have just added quiet boot support for Grub, so I don't think we would need Burg.
