### ISSUE TITLE
[AvdanOS] - Things the OS needs 

### ISSUE THREAD

**Issue by AZProductions** [Avdan-OS/Suggestions#5]
From Avdan-OS/Website
> Sorry, that is not to do with the website but the [main repo](https://github.com/Avdan-OS/AvdanOS) got deleted and the [other repo](https://github.com/Avdan-OS/avdan-os-repository) doesn't allow issues.
> 
> - Screensavers!
> - Hibernation
> - able to run .exe/.msi
- @ProJM1

**Comment by Xapu1337** [comment]
for the exe and msi running that would be just wine, and I would say that the user just can install it by themselves.
or we ship codeweavers crossover by free :troll:

**Comment by proJM1** [comment]
@AZProductions Thanks for making this for me.

**Comment by proJM1** [comment]
> for the exe and msi running that would be just wine, and I would say that the user just can install it by themselves. or we ship codeweavers crossover by free :troll:

Could we have wine preinstalled then?

**Comment by Xapu1337** [comment]
> > for the exe and msi running that would be just wine, and I would say that the user just can install it by themselves. or we ship codeweavers crossover by free :troll:
> 
> Could we have wine preinstalled then?

Yeah seems possible, maybe even with a fitting theme preinstalled

**Comment by Trynera** [comment]
I think the store for avdanos should also have the official wine repo

**Comment by proJM-Coding** [comment]
> I think the store for avdanos should also have the official wine repo

I agree. We should have wine built-in or in a place that it is easy to access and download.

**Comment by StoneMcYT** [comment]
I shall spawn the notion in here 
https://spectacled-wheel-852.notion.site/AvdanOS-Official-Guidelines-and-Documentation-c2069dbbabb24b528e435ba2d5fc88aa

**Comment by proJM-Coding** [comment]
> I shall spawn the notion in here https://spectacled-wheel-852.notion.site/AvdanOS-Official-Guidelines-and-Documentation-c2069dbbabb24b528e435ba2d5fc88aa

Why? We did not break any of the guidelines did we?

**Comment by StoneMcYT** [comment]
> > I shall spawn the notion in here https://spectacled-wheel-852.notion.site/AvdanOS-Official-Guidelines-and-Documentation-c2069dbbabb24b528e435ba2d5fc88aa
> 
> Why? We did not break any of the guidelines did we?

I spawned the notion in  this thread as we made it as our 'todo list' in a sense

**Comment by proJM-Coding** [comment]
Oh, ok.

**Comment by proJM-Coding** [comment]
Another thing I think would be good in the os is folder optimization. This would fit with the theme of avdan os being a productive os. Windows has this feature but it is very unused. We could also take this further and add more ways to optimize folders like a "optimize for programs" option.
![Screenshot (67)](https://user-images.githubusercontent.com/81658610/180131980-da8ef577-a518-48ec-98a8-ef26daba2e31.png)

**Comment by proJM-Coding** [comment]
@StoneMcYT Should I close the issue or just leave it?

**Comment by StoneMcYT** [comment]
Yes I think closing it would makes more sense will close it when I get home though and move it off the roadmap

**Comment by proJM-Coding** [comment]
ok, thanks for you time

**Comment by proJM-Coding** [comment]
@AZProductions can you close the issue?
