### ISSUE TITLE
AvdanOS - Custom Code - OSS

### ISSUE THREAD

**Issue by MrSerge01** [Avdan-OS/suggestions#6]
I thought about a preinstalled on Code - OSS that makes it look more AvdanOS-ish and remove the original VSC tabs in favor of:
1. More c o d e space.
2. Move them files to the AvdanOS tabs on top.

**Comment by Sammy99jsp** [comment]
In order to achieve this we would need:

1. To add an API to enable custom 'Synthetic' Tabs, which are not for switching applications.
2. Implement this API in an extension for VS Code.

**Comment by Xapu1337** [comment]
And possibly ship a custom theme too, but to make this possible we would need to install 2 extensions by default

**Comment by akane6704** [comment]
> And possibly ship a custom theme too, but to make this possible we would need to install 2 extensions by default
I think today i'll start working on theme!

**Comment by akane6704** [comment]
Okay the theme is done you can close this suggestion

**Comment by akane6704** [comment]
https://github.com/akane6704/avdanos-vscode-theme

**Comment by StoneMcYT** [comment]
Closed:
Reason @akane6704  manged to develop a VS code theme to reach the needs of this issue.
https://github.com/akane6704/avdanos-vscode-theme

**Comment by Trynera** [comment]
I disagree. Because this OS isn't only made for Developers, so for average people that would be total bloatware

**Comment by StoneMcYT** [comment]
@Trynera  <----- I would agree with  this chap since its well for all people and not a specific group so I will now close this suggestion

**Comment by MrSerge01** [comment]
> I disagree. Because this OS isn't only made for Developers, so for average people that would be total bloatware

optional software exists, ever saw it?
